on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: 'Login to Docker'
        run: docker login --username ${{ secrets.DOCKER_USER_NAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Check files'
        run: ls

      - name: 'Build Image'
        run: docker build -t ${{ secrets.DOCKER_USER_NAME }}/yahia-ahmed-2023040281 .

      - name: 'Push the Image'
        run: docker push ${{ secrets.DOCKER_USER_NAME }}/yahia-ahmed-2023040281